name: CI
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  createRequestToMyEndpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Make a request to the endpoint
        run: curl https://laboratory-ie-guards-mortgage.trycloudflare.com/
  
