name: Context
on: workflow_dispatch
jobs:
  getContext:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: hello_world
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Get context
        run: echo ${{ env.MY_SECRET }}
