name: Frontend CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  runTests:
    runs-on: ubuntu-18.04
    steps:
      - name: Get repository code
        run: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test app
        run: npm run test
