name: Frontend CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  runTests:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci